#############################################################################
# Makefile for building: KeyBoardSwitcher.app/Contents/MacOS/KeyBoardSwitcher
# Generated by qmake (3.1) (Qt 5.12.6)
# Project:  KeyBoardSwitcher.pro
# Template: app
# Command: /Applications/QT/5.12.6/clang_64/bin/qmake -o Makefile KeyBoardSwitcher.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/QT/5.12.6/clang_64/mkspecs/macx-clang -F/Applications/QT/5.12.6/clang_64/lib
QMAKE         = /Applications/QT/5.12.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Applications/QT/5.12.6/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Applications/QT/5.12.6/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = KeyBoardSwitcher1.0.0
DISTDIR = /Users/v1z/Downloads/Trash/KeyboardSwitcherSource/.tmp/KeyBoardSwitcher1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -F/System/Library/Frameworks/ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Applications/QT/5.12.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/QT/5.12.6/clang_64/lib -framework AppKit -framework Carbon -framework Foundation -framework ApplicationServices -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = adminaccessinstructions.cpp \
		main.cpp \
		mainwindow.cpp \
		switchKeyBoard.mm \
		utilities.cpp qrc_imgs.cpp \
		moc_adminaccessinstructions.cpp \
		moc_mainwindow.cpp \
		moc_utilities.cpp
OBJECTS       = adminaccessinstructions.o \
		main.o \
		mainwindow.o \
		switchKeyBoard.o \
		utilities.o \
		qrc_imgs.o \
		moc_adminaccessinstructions.o \
		moc_mainwindow.o \
		moc_utilities.o
DIST          = icon.png \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/sanitize.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/spec_post.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/toolchain.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/mac.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qt.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/resources.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/moc.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/uic.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/file_copies.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/lex.prf \
		KeyBoardSwitcher.pro adminaccessinstructions.h \
		mainwindow.h \
		switchkeyboard.h \
		utilities.h adminaccessinstructions.cpp \
		main.cpp \
		mainwindow.cpp \
		switchKeyBoard.mm \
		utilities.cpp
QMAKE_TARGET  = KeyBoardSwitcher
DESTDIR       = 
TARGET        = KeyBoardSwitcher.app/Contents/MacOS/KeyBoardSwitcher

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/v1z/Downloads/Trash/KeyboardSwitcherSource/KeyBoardSwitcher.pro


include /Applications/QT/5.12.6/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

KeyBoardSwitcher.app/Contents/MacOS/KeyBoardSwitcher: ./KeyBoardSwitcher.app/Contents/Info.plist ui_adminaccessinstructions.h ui_mainwindow.h $(OBJECTS)  
	@test -d KeyBoardSwitcher.app/Contents/MacOS/ || mkdir -p KeyBoardSwitcher.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: KeyBoardSwitcher.pro /Applications/QT/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf /Applications/QT/5.12.6/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/sanitize.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/spec_post.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/toolchain.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/mac.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qt.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/resources.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/moc.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/uic.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/file_copies.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.12.6/clang_64/mkspecs/features/lex.prf \
		KeyBoardSwitcher.pro \
		imgs.qrc \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile KeyBoardSwitcher.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Applications/QT/5.12.6/clang_64/mkspecs/features/spec_pre.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/qdevice.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/features/device_config.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/common/unix.conf:
/Applications/QT/5.12.6/clang_64/mkspecs/common/mac.conf:
/Applications/QT/5.12.6/clang_64/mkspecs/common/macx.conf:
/Applications/QT/5.12.6/clang_64/mkspecs/common/sanitize.conf:
/Applications/QT/5.12.6/clang_64/mkspecs/common/gcc-base.conf:
/Applications/QT/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/QT/5.12.6/clang_64/mkspecs/common/clang.conf:
/Applications/QT/5.12.6/clang_64/mkspecs/common/clang-mac.conf:
/Applications/QT/5.12.6/clang_64/mkspecs/qconfig.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/QT/5.12.6/clang_64/mkspecs/features/qt_functions.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/qt_config.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/spec_post.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/toolchain.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/default_pre.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/resolve_config.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/default_post.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/qml_debug.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/mac.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/warn_on.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/qt.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/resources.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/moc.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/uic.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/unix/thread.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/qmake_use.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/file_copies.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/rez.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/exceptions.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/yacc.prf:
/Applications/QT/5.12.6/clang_64/mkspecs/features/lex.prf:
KeyBoardSwitcher.pro:
imgs.qrc:
/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile KeyBoardSwitcher.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

KeyBoardSwitcher.app/Contents/PkgInfo: 
	@test -d KeyBoardSwitcher.app/Contents || mkdir -p KeyBoardSwitcher.app/Contents
	@$(DEL_FILE) KeyBoardSwitcher.app/Contents/PkgInfo
	@echo "APPL????" > KeyBoardSwitcher.app/Contents/PkgInfo
KeyBoardSwitcher.app/Contents/Resources/empty.lproj: 
	@test -d KeyBoardSwitcher.app/Contents/Resources || mkdir -p KeyBoardSwitcher.app/Contents/Resources
	@touch KeyBoardSwitcher.app/Contents/Resources/empty.lproj
	
KeyBoardSwitcher.app/Contents/Info.plist: 
	@test -d KeyBoardSwitcher.app/Contents || mkdir -p KeyBoardSwitcher.app/Contents
	@$(DEL_FILE) KeyBoardSwitcher.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,v1z.KeyBoardSwitcher,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},v1z.KeyBoardSwitcher,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,logo.icns,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},logo.icns,g" -e "s,@EXECUTABLE@,KeyBoardSwitcher,g" -e "s,@LIBRARY@,KeyBoardSwitcher,g" -e "s,\$${EXECUTABLE_NAME},KeyBoardSwitcher,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" Info.plist >KeyBoardSwitcher.app/Contents/Info.plist
KeyBoardSwitcher.app/Contents/Resources/logo.icns: logo.icns
	@test -d KeyBoardSwitcher.app/Contents/Resources/ || mkdir -p KeyBoardSwitcher.app/Contents/Resources/
	@$(DEL_FILE) KeyBoardSwitcher.app/Contents/Resources/logo.icns
	@$(COPY_FILE) logo.icns KeyBoardSwitcher.app/Contents/Resources/logo.icns

all: Makefile \
		KeyBoardSwitcher.app/Contents/PkgInfo \
		KeyBoardSwitcher.app/Contents/Resources/empty.lproj \
		KeyBoardSwitcher.app/Contents/Info.plist \
		KeyBoardSwitcher.app/Contents/Resources/logo.icns KeyBoardSwitcher.app/Contents/MacOS/KeyBoardSwitcher

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents imgs.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /Applications/QT/5.12.6/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents adminaccessinstructions.h mainwindow.h switchkeyboard.h utilities.h $(DISTDIR)/
	$(COPY_FILE) --parents adminaccessinstructions.cpp main.cpp mainwindow.cpp switchKeyBoard.mm utilities.cpp $(DISTDIR)/
	$(COPY_FILE) --parents adminaccessinstructions.ui mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r KeyBoardSwitcher.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

./KeyBoardSwitcher.app/Contents/Info.plist: /Users/v1z/Downloads/Trash/KeyboardSwitcherSource/Info.plist
	$(DEL_FILE) "./KeyBoardSwitcher.app/Contents/Info.plist" 
	 $(COPY_FILE) /Users/v1z/Downloads/Trash/KeyboardSwitcherSource/Info.plist "./KeyBoardSwitcher.app/Contents/Info.plist"

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_imgs.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_imgs.cpp
qrc_imgs.cpp: imgs.qrc \
		/Applications/QT/5.12.6/clang_64/bin/rcc \
		icon.png \
		imgAddAdmin.png \
		logo.icns \
		../build-last/logo.icns
	/Applications/QT/5.12.6/clang_64/bin/rcc -name imgs imgs.qrc -o qrc_imgs.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Applications/QT/5.12.6/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h /Applications/QT/5.12.6/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_adminaccessinstructions.cpp moc_mainwindow.cpp moc_utilities.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_adminaccessinstructions.cpp moc_mainwindow.cpp moc_utilities.cpp
moc_adminaccessinstructions.cpp: adminaccessinstructions.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		/Applications/QT/5.12.6/clang_64/bin/moc
	/Applications/QT/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/v1z/Downloads/Trash/KeyboardSwitcherSource/moc_predefs.h -I/Applications/QT/5.12.6/clang_64/mkspecs/macx-clang -I/Users/v1z/Downloads/Trash/KeyboardSwitcherSource -I/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Applications/QT/5.12.6/clang_64/lib adminaccessinstructions.h -o moc_adminaccessinstructions.cpp

moc_mainwindow.cpp: mainwindow.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		moc_predefs.h \
		/Applications/QT/5.12.6/clang_64/bin/moc
	/Applications/QT/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/v1z/Downloads/Trash/KeyboardSwitcherSource/moc_predefs.h -I/Applications/QT/5.12.6/clang_64/mkspecs/macx-clang -I/Users/v1z/Downloads/Trash/KeyboardSwitcherSource -I/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Applications/QT/5.12.6/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_utilities.cpp: utilities.h \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/QThread \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/qthread.h \
		moc_predefs.h \
		/Applications/QT/5.12.6/clang_64/bin/moc
	/Applications/QT/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/v1z/Downloads/Trash/KeyboardSwitcherSource/moc_predefs.h -I/Applications/QT/5.12.6/clang_64/mkspecs/macx-clang -I/Users/v1z/Downloads/Trash/KeyboardSwitcherSource -I/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Applications/QT/5.12.6/clang_64/lib utilities.h -o moc_utilities.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_adminaccessinstructions.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_adminaccessinstructions.h ui_mainwindow.h
ui_adminaccessinstructions.h: adminaccessinstructions.ui \
		/Applications/QT/5.12.6/clang_64/bin/uic
	/Applications/QT/5.12.6/clang_64/bin/uic adminaccessinstructions.ui -o ui_adminaccessinstructions.h

ui_mainwindow.h: mainwindow.ui \
		/Applications/QT/5.12.6/clang_64/bin/uic
	/Applications/QT/5.12.6/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

adminaccessinstructions.o: adminaccessinstructions.cpp adminaccessinstructions.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_adminaccessinstructions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminaccessinstructions.o adminaccessinstructions.cpp

main.o: main.cpp mainwindow.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/QProcess \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/qprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers/QCloseEvent \
		/Applications/QT/5.12.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		ui_mainwindow.h \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/QDir \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/qdir.h \
		switchkeyboard.h \
		utilities.h \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/QThread \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		adminaccessinstructions.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QSystemTrayIcon \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMenu \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/QT/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/QProcess \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/qprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

switchKeyBoard.o: switchKeyBoard.mm 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o switchKeyBoard.o switchKeyBoard.mm

utilities.o: utilities.cpp switchkeyboard.h \
		utilities.h \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/QThread \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/QT/5.12.6/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utilities.o utilities.cpp

qrc_imgs.o: qrc_imgs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_imgs.o qrc_imgs.cpp

moc_adminaccessinstructions.o: moc_adminaccessinstructions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminaccessinstructions.o moc_adminaccessinstructions.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_utilities.o: moc_utilities.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_utilities.o moc_utilities.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/KeyBoardSwitcher/bin || mkdir -p $(INSTALL_ROOT)/opt/KeyBoardSwitcher/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/KeyBoardSwitcher/bin/KeyBoardSwitcher.app
	
	-$(QINSTALL) KeyBoardSwitcher.app $(INSTALL_ROOT)/opt/KeyBoardSwitcher/bin/KeyBoardSwitcher.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/KeyBoardSwitcher/bin/KeyBoardSwitcher.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/KeyBoardSwitcher/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

